package report

import (
	"fmt"
	"strings"
	"time"

	"github.com/shardc2/shardc2/internal/database"
)

type CampaignReport struct {
	Name         string
	Type         string
	Status       string
	CreatedAt    time.Time
	Config       string
	CommandCount int
	ResultCount  int
	SuccessCount int
	FailedCount  int
	AuditEvents  []AuditEntry
}

type AuditEntry struct {
	Action    string
	Operator  string
	Outcome   string
	Timestamp time.Time
}

func GenerateCampaignReport(db *database.DB, campaignID string) (string, error) {
	var r CampaignReport
	err := db.QueryRow(`
		SELECT name, type, status, COALESCE(config::text, '{}'), created_at
		FROM campaigns WHERE id = $1`, campaignID,
	).Scan(&r.Name, &r.Type, &r.Status, &r.Config, &r.CreatedAt)
	if err != nil {
		return "", fmt.Errorf("campaign not found: %w", err)
	}

	db.QueryRow(`SELECT COUNT(*) FROM commands WHERE campaign_id = $1`, campaignID).Scan(&r.CommandCount)
	db.QueryRow(`SELECT COUNT(*) FROM commands WHERE campaign_id = $1 AND status = 'completed'`, campaignID).Scan(&r.SuccessCount)
	db.QueryRow(`SELECT COUNT(*) FROM commands WHERE campaign_id = $1 AND status = 'failed'`, campaignID).Scan(&r.FailedCount)
	r.ResultCount = r.SuccessCount + r.FailedCount

	rows, err := db.Query(`
		SELECT action, COALESCE(operator_username, ''), outcome, created_at
		FROM audit_events
		WHERE object_type = 'campaign' AND object_id = $1
		ORDER BY created_at`, campaignID)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var e AuditEntry
			if err := rows.Scan(&e.Action, &e.Operator, &e.Outcome, &e.Timestamp); err == nil {
				r.AuditEvents = append(r.AuditEvents, e)
			}
		}
	}

	return renderMarkdown(campaignID, r), nil
}

func renderMarkdown(id string, r CampaignReport) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Campaign Report: %s\n\n", r.Name))
	sb.WriteString(fmt.Sprintf("**ID:** `%s`\n", id))
	sb.WriteString(fmt.Sprintf("**Type:** %s\n", r.Type))
	sb.WriteString(fmt.Sprintf("**Status:** %s\n", r.Status))
	sb.WriteString(fmt.Sprintf("**Created:** %s\n\n", r.CreatedAt.Format(time.RFC3339)))

	sb.WriteString("## Configuration\n\n")
	sb.WriteString(fmt.Sprintf("```json\n%s\n```\n\n", r.Config))

	sb.WriteString("## Command Summary\n\n")
	sb.WriteString(fmt.Sprintf("| Metric | Count |\n|---|---|\n"))
	sb.WriteString(fmt.Sprintf("| Total Commands | %d |\n", r.CommandCount))
	sb.WriteString(fmt.Sprintf("| Completed | %d |\n", r.SuccessCount))
	sb.WriteString(fmt.Sprintf("| Failed | %d |\n", r.FailedCount))
	sb.WriteString(fmt.Sprintf("| Pending | %d |\n\n", r.CommandCount-r.ResultCount))

	if len(r.AuditEvents) > 0 {
		sb.WriteString("## Audit Trail\n\n")
		sb.WriteString("| Time | Action | Operator | Outcome |\n|---|---|---|---|\n")
		for _, e := range r.AuditEvents {
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", e.Timestamp.Format(time.RFC3339), e.Action, e.Operator, e.Outcome))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("---\n*Generated by ShardC2 at %s*\n", time.Now().UTC().Format(time.RFC3339)))
	return sb.String()
}
