package report

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/shardc2/shardc2/internal/database"
)

type CampaignReport struct {
	Name         string
	Type         string
	Status       string
	CreatedAt    time.Time
	Config       string
	CommandCount int
	ResultCount  int
	SuccessCount int
	FailedCount  int
	AuditEvents  []AuditEntry
}

type AuditEntry struct {
	Action    string
	Operator  string
	Outcome   string
	Timestamp time.Time
}

func GenerateCampaignReport(db *database.DB, campaignID string) (string, error) {
	var r CampaignReport
	err := db.QueryRow(`
		SELECT name, type, status, COALESCE(config::text, '{}'), created_at
		FROM campaigns WHERE id = $1`, campaignID,
	).Scan(&r.Name, &r.Type, &r.Status, &r.Config, &r.CreatedAt)
	if err != nil {
		return "", fmt.Errorf("campaign not found: %w", err)
	}

	db.QueryRow(`SELECT COUNT(*) FROM commands WHERE campaign_id = $1`, campaignID).Scan(&r.CommandCount)
	db.QueryRow(`SELECT COUNT(*) FROM commands WHERE campaign_id = $1 AND status = 'completed'`, campaignID).Scan(&r.SuccessCount)
	db.QueryRow(`SELECT COUNT(*) FROM commands WHERE campaign_id = $1 AND status = 'failed'`, campaignID).Scan(&r.FailedCount)
	r.ResultCount = r.SuccessCount + r.FailedCount

	rows, err := db.Query(`
		SELECT action, COALESCE(operator_username, ''), outcome, created_at
		FROM audit_events
		WHERE object_type = 'campaign' AND object_id = $1
		ORDER BY created_at`, campaignID)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var e AuditEntry
			if err := rows.Scan(&e.Action, &e.Operator, &e.Outcome, &e.Timestamp); err == nil {
				r.AuditEvents = append(r.AuditEvents, e)
			}
		}
	}

	return renderMarkdown(campaignID, r), nil
}

func renderMarkdown(id string, r CampaignReport) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Campaign Report: %s\n\n", r.Name))
	sb.WriteString(fmt.Sprintf("**ID:** `%s`\n", id))
	sb.WriteString(fmt.Sprintf("**Type:** %s\n", r.Type))
	sb.WriteString(fmt.Sprintf("**Status:** %s\n", r.Status))
	sb.WriteString(fmt.Sprintf("**Created:** %s\n\n", r.CreatedAt.Format(time.RFC3339)))

	sb.WriteString("## Configuration\n\n")
	sb.WriteString(fmt.Sprintf("```json\n%s\n```\n\n", r.Config))

	sb.WriteString("## Command Summary\n\n")
	sb.WriteString(fmt.Sprintf("| Metric | Count |\n|---|---|\n"))
	sb.WriteString(fmt.Sprintf("| Total Commands | %d |\n", r.CommandCount))
	sb.WriteString(fmt.Sprintf("| Completed | %d |\n", r.SuccessCount))
	sb.WriteString(fmt.Sprintf("| Failed | %d |\n", r.FailedCount))
	sb.WriteString(fmt.Sprintf("| Pending | %d |\n\n", r.CommandCount-r.ResultCount))

	if len(r.AuditEvents) > 0 {
		sb.WriteString("## Audit Trail\n\n")
		sb.WriteString("| Time | Action | Operator | Outcome |\n|---|---|---|---|\n")
		for _, e := range r.AuditEvents {
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", e.Timestamp.Format(time.RFC3339), e.Action, e.Operator, e.Outcome))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("---\n*Generated by ShardC2 at %s*\n", time.Now().UTC().Format(time.RFC3339)))
	return sb.String()
}

// --- JSON Report ---

type jsonReport struct {
	CampaignID  string          `json:"campaign_id"`
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	Status      string          `json:"status"`
	CreatedAt   time.Time       `json:"created_at"`
	Config      json.RawMessage `json:"config"`
	Tasks       []jsonTask      `json:"tasks"`
	Credentials []jsonCred      `json:"credentials"`
	AuditTrail  []jsonAudit     `json:"audit_trail"`
	GeneratedAt time.Time       `json:"generated_at"`
}

type jsonTask struct {
	TaskName    string     `json:"task_name"`
	BotID       string     `json:"bot_id"`
	Status      string     `json:"status"`
	Output      string     `json:"output"`
	CompletedAt *time.Time `json:"completed_at"`
}

type jsonCred struct {
	Username     string    `json:"username"`
	Target       string    `json:"target"`
	Port         int       `json:"port"`
	Service      string    `json:"service"`
	Valid        bool      `json:"valid"`
	DiscoveredAt time.Time `json:"discovered_at"`
}

type jsonAudit struct {
	Action    string    `json:"action"`
	Operator  string    `json:"operator"`
	Outcome   string    `json:"outcome"`
	Timestamp time.Time `json:"timestamp"`
}

func GenerateJSONReport(db *database.DB, campaignID string) ([]byte, error) {
	var rpt jsonReport
	rpt.CampaignID = campaignID
	var configRaw string
	err := db.QueryRow(`
		SELECT name, type, status, COALESCE(config::text, '{}'), created_at
		FROM campaigns WHERE id = $1`, campaignID,
	).Scan(&rpt.Name, &rpt.Type, &rpt.Status, &configRaw, &rpt.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("campaign not found: %w", err)
	}
	rpt.Config = json.RawMessage(configRaw)

	// Tasks
	rows, err := db.Query(`
		SELECT task_name, COALESCE(bot_id::text, ''), status, COALESCE(output, ''), completed_at
		FROM campaign_tasks
		WHERE campaign_id = $1
		ORDER BY created_at`, campaignID)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var t jsonTask
			var completed *time.Time
			if err := rows.Scan(&t.TaskName, &t.BotID, &t.Status, &t.Output, &completed); err == nil {
				t.CompletedAt = completed
				rpt.Tasks = append(rpt.Tasks, t)
			}
		}
	}

	// Credentials discovered during campaign (by bots assigned to this campaign)
	credRows, err := db.Query(`
		SELECT DISTINCT c.username, c.target, c.port, COALESCE(c.service, 'ssh'), c.valid, c.discovered_at
		FROM credentials c
		WHERE c.bot_id IN (SELECT bot_id FROM campaign_tasks WHERE campaign_id = $1)
		  AND c.discovered_at >= (SELECT created_at FROM campaigns WHERE id = $1)
		ORDER BY c.discovered_at`, campaignID)
	if err == nil {
		defer credRows.Close()
		for credRows.Next() {
			var cr jsonCred
			if err := credRows.Scan(&cr.Username, &cr.Target, &cr.Port, &cr.Service, &cr.Valid, &cr.DiscoveredAt); err == nil {
				rpt.Credentials = append(rpt.Credentials, cr)
			}
		}
	}

	// Audit trail
	auditRows, err := db.Query(`
		SELECT action, COALESCE(operator_username, ''), outcome, created_at
		FROM audit_events
		WHERE object_type = 'campaign' AND object_id = $1
		ORDER BY created_at`, campaignID)
	if err == nil {
		defer auditRows.Close()
		for auditRows.Next() {
			var a jsonAudit
			if err := auditRows.Scan(&a.Action, &a.Operator, &a.Outcome, &a.Timestamp); err == nil {
				rpt.AuditTrail = append(rpt.AuditTrail, a)
			}
		}
	}

	// Ensure non-nil slices for clean JSON
	if rpt.Tasks == nil {
		rpt.Tasks = []jsonTask{}
	}
	if rpt.Credentials == nil {
		rpt.Credentials = []jsonCred{}
	}
	if rpt.AuditTrail == nil {
		rpt.AuditTrail = []jsonAudit{}
	}

	rpt.GeneratedAt = time.Now().UTC()
	return json.MarshalIndent(rpt, "", "  ")
}

// --- HTML Report ---

func GenerateHTMLReport(db *database.DB, campaignID string) (string, error) {
	// Reuse JSON report data for consistency
	data, err := GenerateJSONReport(db, campaignID)
	if err != nil {
		return "", err
	}
	var rpt jsonReport
	if err := json.Unmarshal(data, &rpt); err != nil {
		return "", fmt.Errorf("internal error: %w", err)
	}
	return renderHTML(rpt), nil
}

func statusBadge(status string) string {
	color := "#c5c8d4"
	switch strings.ToLower(status) {
	case "completed", "active", "success":
		color = "#00ff88"
	case "failed", "error":
		color = "#ff3333"
	case "pending", "paused":
		color = "#ffcc00"
	}
	return fmt.Sprintf(`<span style="background:%s;color:#0a0e17;padding:2px 8px;border-radius:4px;font-weight:bold;font-size:0.85em;">%s</span>`, color, html.EscapeString(status))
}

func renderHTML(rpt jsonReport) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ShardC2 Campaign Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #0a0e17; color: #c5c8d4; font-family: monospace; padding: 2em; line-height: 1.6; }
  h1 { color: #ff3333; border-bottom: 2px solid #ff3333; padding-bottom: 0.3em; margin-bottom: 1em; }
  h2 { color: #00ff88; margin-top: 1.5em; margin-bottom: 0.5em; }
  .meta { margin-bottom: 1.5em; }
  .meta span { display: inline-block; margin-right: 2em; }
  .meta .label { color: #ffcc00; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 1.5em; }
  th { background: #151b2b; color: #ff3333; text-align: left; padding: 8px 12px; border: 1px solid #2a3050; }
  td { padding: 8px 12px; border: 1px solid #2a3050; vertical-align: top; }
  tr:nth-child(even) { background: #0f1320; }
  tr:hover { background: #1a2035; }
  pre { background: #0f1320; padding: 1em; border: 1px solid #2a3050; overflow-x: auto; white-space: pre-wrap; word-break: break-all; margin-bottom: 1em; }
  .badge { padding: 2px 8px; border-radius: 4px; font-weight: bold; font-size: 0.85em; color: #0a0e17; }
  .footer { margin-top: 2em; padding-top: 1em; border-top: 1px solid #2a3050; color: #666; font-size: 0.85em; }
  .output-cell { max-height: 200px; overflow-y: auto; }
</style>
</head>
<body>
`)

	sb.WriteString(fmt.Sprintf("<h1>Campaign Report: %s</h1>\n", html.EscapeString(rpt.Name)))

	sb.WriteString(`<div class="meta">`)
	sb.WriteString(fmt.Sprintf(`<span><span class="label">ID:</span> %s</span>`, html.EscapeString(rpt.CampaignID)))
	sb.WriteString(fmt.Sprintf(`<span><span class="label">Type:</span> %s</span>`, html.EscapeString(rpt.Type)))
	sb.WriteString(fmt.Sprintf(`<span><span class="label">Status:</span> %s</span>`, statusBadge(rpt.Status)))
	sb.WriteString(fmt.Sprintf(`<span><span class="label">Created:</span> %s</span>`, rpt.CreatedAt.Format(time.RFC3339)))
	sb.WriteString("</div>\n")

	// Config
	sb.WriteString("<h2>Configuration</h2>\n")
	var prettyConfig bytes.Buffer
	if err := json.Indent(&prettyConfig, rpt.Config, "", "  "); err == nil {
		sb.WriteString(fmt.Sprintf("<pre>%s</pre>\n", html.EscapeString(prettyConfig.String())))
	} else {
		sb.WriteString(fmt.Sprintf("<pre>%s</pre>\n", html.EscapeString(string(rpt.Config))))
	}

	// Tasks
	sb.WriteString(fmt.Sprintf("<h2>Tasks (%d)</h2>\n", len(rpt.Tasks)))
	if len(rpt.Tasks) > 0 {
		sb.WriteString("<table>\n<tr><th>Task</th><th>Bot ID</th><th>Status</th><th>Output</th><th>Completed</th></tr>\n")
		for _, t := range rpt.Tasks {
			completed := ""
			if t.CompletedAt != nil {
				completed = t.CompletedAt.Format(time.RFC3339)
			}
			output := html.EscapeString(t.Output)
			if len(output) > 500 {
				output = output[:500] + "..."
			}
			sb.WriteString(fmt.Sprintf("<tr><td>%s</td><td><code>%s</code></td><td>%s</td><td class=\"output-cell\"><pre>%s</pre></td><td>%s</td></tr>\n",
				html.EscapeString(t.TaskName),
				html.EscapeString(t.BotID),
				statusBadge(t.Status),
				output,
				completed,
			))
		}
		sb.WriteString("</table>\n")
	} else {
		sb.WriteString("<p>No tasks recorded.</p>\n")
	}

	// Credentials
	sb.WriteString(fmt.Sprintf("<h2>Credentials (%d)</h2>\n", len(rpt.Credentials)))
	if len(rpt.Credentials) > 0 {
		sb.WriteString("<table>\n<tr><th>Username</th><th>Target</th><th>Port</th><th>Service</th><th>Valid</th><th>Discovered</th></tr>\n")
		for _, cr := range rpt.Credentials {
			validBadge := statusBadge("failed")
			if cr.Valid {
				validBadge = statusBadge("completed")
			}
			sb.WriteString(fmt.Sprintf("<tr><td>%s</td><td>%s</td><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
				html.EscapeString(cr.Username),
				html.EscapeString(cr.Target),
				cr.Port,
				html.EscapeString(cr.Service),
				validBadge,
				cr.DiscoveredAt.Format(time.RFC3339),
			))
		}
		sb.WriteString("</table>\n")
	} else {
		sb.WriteString("<p>No credentials discovered.</p>\n")
	}

	// Audit trail
	sb.WriteString(fmt.Sprintf("<h2>Audit Trail (%d)</h2>\n", len(rpt.AuditTrail)))
	if len(rpt.AuditTrail) > 0 {
		sb.WriteString("<table>\n<tr><th>Time</th><th>Action</th><th>Operator</th><th>Outcome</th></tr>\n")
		for _, a := range rpt.AuditTrail {
			sb.WriteString(fmt.Sprintf("<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
				a.Timestamp.Format(time.RFC3339),
				html.EscapeString(a.Action),
				html.EscapeString(a.Operator),
				statusBadge(a.Outcome),
			))
		}
		sb.WriteString("</table>\n")
	} else {
		sb.WriteString("<p>No audit events recorded.</p>\n")
	}

	sb.WriteString(fmt.Sprintf(`<div class="footer">Generated by ShardC2 at %s</div>`, time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString("\n</body>\n</html>\n")

	return sb.String()
}
